version: '3'
services:
  node-app:
    build:
      context: . # Path to your Node.js app's Dockerfile and source code
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: mongodb://mongo:27017/your-database-name  # Use the hostname 'mongo' to connect to the MongoDB service

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

